name: 'GitHub Action for ktint'
description: 'A tool to enforce Kotlin style and conventions'
author: 'Yutaro Muta'
inputs:
  xml_path:
    description: 'The file path of the XML lint report'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
