name: "release"
on:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  release_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        npm install
        npm run all